# -*- coding: utf-8 -*-
"""Funções.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uPgd-OolzL-LYHCPzdlMk5zd3msHlteK

# Funções

São bloco de códigos reutilizáveis que executam uma determinada tarefa.

- podem ser definidas pelo programador
- podem ser built-in (internas do Python)
- podem ser de terceiros (pacotes)
- são criadas com a palavra reservada **def** (definition)

# Criando uma função simples
"""

print('Seja bem vindo(a) à Empowerdata!')
print('Você está logado(a) no sistema!')
print('Não se esqueça de fazer o logout!')

def imprimir_frases():
  print('Seja bem vindo(a) à Empowerpython!')
  print('Você está logado(a) no sistema!')
  print('Não se esqueça de fazer o logout!')

imprimir_frases()

imprimir_frases()

"""# Criando uma função com parâmetros

Parâmetros são valores que podemos passar para uma função.
"""

print('Seja bem vindo(a) à Empowerdata, Vinicius!')
print('Você está logado(a) no sistema Vinicius!')
print('Não se esqueça de fazer o logout Vinicius!')

def imprimir_frases_usuario(nome):
  print(f'Seja bem vindo(a) à Empowerdata, {nome}!')
  print(f'Você está logado(a) no sistema {nome}!')
  print(f'Não se esqueça de fazer o logout {nome}!')

imprimir_frases_usuario('Vinicius')

imprimir_frases_usuario('Ana')

def somar_numeros(numero1, numero2):
  print(numero1 + numero2)

somar_numeros(10, 15)

somar_numeros(1000, 50)

"""# Escopo de variáveis em funções

====>>>> **Variáveis declaradas dentro de uma função só são visíveis dentro do bloco da função!**
"""

nome_teste = 'Python'

def imprimir_frases_usuario(nome):

  nome_usuario = nome + '!'

  print(f'Seja bem vindo(a) à Empowerdata, {nome_usuario}')
  print(f'Você está logado(a) no sistema {nome_usuario}')
  print(f'Não se esqueça de fazer o logout {nome_usuario}')

imprimir_frases_usuario('Vinicius')

print(nome_usuario)

print(nome_teste)

"""# Retornos

Funções podem retornar um valor. Para isso utilizamos a palavra reservada **return**.
"""

def somar_numeros(numero1, numero2):
  return numero1 + numero2

somar_numeros(10, 20)

resultado = somar_numeros(100, 300)

print(resultado)

def somar_numeros(numero1, numero2):
  resultado = numero1 + numero2
  return resultado

resultado2 = somar_numeros(1000, 100)

def calculos(numero1, numero2):
  soma = numero1 + numero2
  multiplicacao = numero1 * numero1
  exponenciacao = numero1 ** numero2

  return soma, multiplicacao, exponenciacao

calculos(10, 2)

resultados = calculos(10, 3)

print(resultados)

type(resultados)

"""# Funções built-in (internas)"""

print('Vinicius')

type('Vinicius')

abs(-10)

bin(13)

lista = [1, 2, 3, 4, 5, 6, 7]

len(lista)

"""# Funções de terceiros"""

import pandas as pd

dados = {
    'nome': ['Vinicius', 'Python', 'Empowerdata']
}

type(dados)

df = pd.DataFrame(dados)

df

